# Generated by Django 4.2.4 on 2023-09-06 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_containers_helmets'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessories',
            name='slug',
            field=models.SlugField(default=''),
        ),
        migrations.AddField(
            model_name='catalog',
            name='slug',
            field=models.SlugField(default=''),
        ),
        migrations.AddField(
            model_name='containers',
            name='slug',
            field=models.SlugField(default=''),
        ),
        migrations.AddField(
            model_name='helmets',
            name='slug',
            field=models.SlugField(default=''),
        ),
        migrations.AddField(
            model_name='parachutes',
            name='slug',
            field=models.SlugField(default=''),
        ),
        migrations.AddField(
            model_name='wingsuits',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
