# Generated by Django 4.2.4 on 2023-09-06 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_accessories_slug_catalog_slug_containers_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessories',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='containers',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='helmets',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='parachutes',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='wingsuits',
            name='price',
            field=models.IntegerField(),
        ),
    ]
