# Generated by Django 4.2.4 on 2023-09-07 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_accessories_price_alter_containers_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parachutes',
            name='currency',
            field=models.CharField(choices=[('€', 'Euro'), ('$', 'Dollars')], default='$', max_length=1),
        ),
    ]
