# Generated by Django 4.2.4 on 2023-09-09 17:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_accessories_currency_containers_currency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('message', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='accessories',
            name='description',
            field=models.CharField(default='null', max_length=300),
        ),
        migrations.AlterField(
            model_name='accessories',
            name='price',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='containers',
            name='description',
            field=models.CharField(default='null', max_length=300),
        ),
        migrations.AlterField(
            model_name='containers',
            name='price',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='helmets',
            name='description',
            field=models.CharField(default='null', max_length=300),
        ),
        migrations.AlterField(
            model_name='helmets',
            name='price',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='parachutes',
            name='description',
            field=models.CharField(default='null', max_length=300),
        ),
        migrations.AlterField(
            model_name='parachutes',
            name='price',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='wingsuits',
            name='description',
            field=models.CharField(default='null', max_length=300),
        ),
        migrations.AlterField(
            model_name='wingsuits',
            name='price',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
