# Generated by Django 4.2.4 on 2023-09-10 09:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_alter_messages_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='name',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
    ]
