# Generated by Django 4.2.4 on 2023-09-10 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_customers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='delivery_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
