# Generated by Django 4.2.4 on 2023-09-10 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_alter_customers_phone_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='currency',
            field=models.CharField(choices=[('€', 'Euro'), ('$', 'Dollars')], default='$', max_length=1),
        ),
    ]
