# Generated by Django 4.2.4 on 2023-09-10 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_orders_price_alter_orders_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='cost',
        ),
        migrations.AlterField(
            model_name='orders',
            name='price',
            field=models.IntegerField(),
        ),
    ]
