# Generated by Django 4.2.4 on 2023-09-11 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_remove_orders_cost_alter_orders_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='password',
            field=models.CharField(default='pass', max_length=20),
            preserve_default=False,
        ),
    ]
