# Generated by Django 4.2.4 on 2023-09-11 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_defects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defects',
            name='photo',
            field=models.FileField(upload_to='gallery_tmp'),
        ),
    ]
