# Generated by Django 4.2.4 on 2023-09-13 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_alter_defects_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='parachutes',
            name='image',
            field=models.ImageField(default='-', upload_to='shop/img/Parashutes'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='defects',
            name='photo',
            field=models.FileField(upload_to='defect_photos'),
        ),
    ]
