# Generated by Django 4.2.4 on 2023-09-13 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_parachutes_image_alter_defects_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='parachutes',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='shop.catalog'),
        ),
        migrations.AlterField(
            model_name='defects',
            name='photo',
            field=models.FileField(upload_to='uploads/defect_photos'),
        ),
        migrations.AlterField(
            model_name='parachutes',
            name='image',
            field=models.ImageField(null=True, upload_to='catalog/parashutes'),
        ),
    ]
