# Generated by Django 4.2.4 on 2023-09-13 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_parachutes_category_alter_defects_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessories',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='shop.catalog'),
        ),
        migrations.AddField(
            model_name='accessories',
            name='image',
            field=models.ImageField(null=True, upload_to='catalog/accessories'),
        ),
        migrations.AddField(
            model_name='containers',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='shop.catalog'),
        ),
        migrations.AddField(
            model_name='containers',
            name='image',
            field=models.ImageField(null=True, upload_to='catalog/containers'),
        ),
        migrations.AddField(
            model_name='helmets',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='shop.catalog'),
        ),
        migrations.AddField(
            model_name='helmets',
            name='image',
            field=models.ImageField(null=True, upload_to='catalog/helmets'),
        ),
        migrations.AddField(
            model_name='wingsuits',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='shop.catalog'),
        ),
        migrations.AddField(
            model_name='wingsuits',
            name='image',
            field=models.ImageField(null=True, upload_to='catalog/wingsuits'),
        ),
    ]
