# Generated by Django 4.2.4 on 2023-09-13 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_accessories_category_accessories_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accessories',
            old_name='category',
            new_name='catalog',
        ),
        migrations.RenameField(
            model_name='containers',
            old_name='category',
            new_name='catalog',
        ),
        migrations.RenameField(
            model_name='helmets',
            old_name='category',
            new_name='catalog',
        ),
        migrations.RenameField(
            model_name='parachutes',
            old_name='category',
            new_name='catalog',
        ),
        migrations.RenameField(
            model_name='wingsuits',
            old_name='category',
            new_name='catalog',
        ),
    ]
