# Generated by Django 4.2.4 on 2023-09-13 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_rename_category_accessories_catalog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessories',
            name='name',
            field=models.CharField(default='null', max_length=30),
        ),
    ]
