# Generated by Django 4.2.4 on 2023-09-13 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_alter_accessories_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='containers',
            name='name',
            field=models.CharField(default='null', max_length=30),
        ),
        migrations.AlterField(
            model_name='helmets',
            name='name',
            field=models.CharField(default='null', max_length=30),
        ),
        migrations.AlterField(
            model_name='parachutes',
            name='name',
            field=models.CharField(default='null', max_length=30),
        ),
        migrations.AlterField(
            model_name='wingsuits',
            name='name',
            field=models.CharField(default='null', max_length=30),
        ),
    ]
