# Generated by Django 4.2.4 on 2023-09-13 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_alter_containers_name_alter_helmets_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wingsuits',
            name='description',
            field=models.TextField(),
        ),
    ]
