# Generated by Django 4.2.4 on 2023-09-13 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0029_alter_wingsuits_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessories',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='containers',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='helmets',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='parachutes',
            name='description',
            field=models.TextField(),
        ),
    ]
