# Generated by Django 4.2.4 on 2023-09-13 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0030_alter_accessories_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='defects',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='shop.customers'),
        ),
    ]
