# Generated by Django 4.2.4 on 2023-09-14 11:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0031_defects_customer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Catalog',
            new_name='Categories',
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='null', max_length=30)),
                ('description', models.TextField()),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('currency', models.CharField(choices=[('€', 'Euro'), ('$', 'Dollars')], default='$', max_length=1)),
                ('slug', models.SlugField(default='')),
                ('image', models.ImageField(null=True, upload_to='catalog/parashutes')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='shop.categories')),
            ],
        ),
    ]
