# Generated by Django 4.2.4 on 2023-09-14 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0032_rename_catalog_categories_goods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='image',
            field=models.ImageField(null=True, upload_to='catalog'),
        ),
        migrations.DeleteModel(
            name='Parachutes',
        ),
    ]
