# Generated by Django 4.2.4 on 2023-09-14 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0033_alter_goods_image_delete_parachutes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='containers',
            name='catalog',
        ),
        migrations.RemoveField(
            model_name='helmets',
            name='catalog',
        ),
        migrations.RemoveField(
            model_name='wingsuits',
            name='catalog',
        ),
        migrations.DeleteModel(
            name='Accessories',
        ),
        migrations.DeleteModel(
            name='Containers',
        ),
        migrations.DeleteModel(
            name='Helmets',
        ),
        migrations.DeleteModel(
            name='Wingsuits',
        ),
    ]
