# Generated by Django 4.2.4 on 2023-09-14 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0034_remove_containers_catalog_remove_helmets_catalog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='shop.categories'),
        ),
    ]
