# Generated by Django 4.2.4 on 2023-09-15 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0036_remove_defects_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainPageGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(null=True, upload_to='main page gallery')),
            ],
        ),
    ]
