# Generated by Django 4.2.4 on 2023-09-15 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0037_mainpagegallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('old_price', models.IntegerField()),
                ('new_price', models.IntegerField()),
                ('image', models.ImageField(null=True, upload_to='sales')),
            ],
        ),
    ]
