# Generated by Django 4.2.4 on 2023-09-15 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0039_alter_sales_new_price_alter_sales_old_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='new_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='old_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
