# Generated by Django 4.2.4 on 2023-09-15 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0042_alter_sales_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='slug',
        ),
    ]
