# Generated by Django 4.2.4 on 2023-09-15 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0043_remove_sales_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='new_price',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='old_price',
        ),
    ]
