# Generated by Django 4.2.4 on 2023-09-16 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0044_remove_sales_new_price_remove_sales_old_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='new_price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
