# Generated by Django 4.2.4 on 2023-09-16 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0045_sales_new_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='name',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='shop.goods'),
        ),
    ]
