# Generated by Django 4.2.4 on 2023-09-16 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0046_alter_sales_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='good',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='shop.goods'),
        ),
    ]
