# Generated by Django 4.2.4 on 2023-09-17 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0050_alter_shoppingcart_good_alter_shoppingcart_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='currency',
            field=models.CharField(choices=[('€', 'Euro'), ('$', 'Dollars')], default='$', max_length=1),
        ),
    ]
