# Generated by Django 4.2.4 on 2023-09-17 19:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0051_alter_shoppingcart_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='category',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='customer',
        ),
        migrations.AddField(
            model_name='orders',
            name='cost',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='good_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='shop.goods'),
        ),
        migrations.AddField(
            model_name='orders',
            name='phone',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='total_order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='user',
            field=models.CharField(default='null', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orders',
            name='good',
            field=models.CharField(default=3465465464, max_length=200),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Customers',
        ),
    ]
