# Generated by Django 4.2.4 on 2023-09-17 19:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0054_rename_gd_id_orders_gd_rename_us_id_orders_us'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='gd',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='us',
        ),
        migrations.AlterField(
            model_name='orders',
            name='good',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='shop.goods'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
