# Generated by Django 4.2.4 on 2023-09-18 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0055_remove_orders_gd_remove_orders_us_alter_orders_good_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField(null=True)),
                ('cost', models.IntegerField(null=True)),
                ('total_order', models.IntegerField(null=True)),
                ('currency', models.CharField(choices=[('€', 'Euro'), ('$', 'Dollars')], default='$', max_length=1)),
                ('good', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='shop.goods')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
