# Generated by Django 4.2.4 on 2023-09-18 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0057_orders_orderdetails_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetails',
            old_name='total_order',
            new_name='total',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='total_order',
            new_name='total',
        ),
        migrations.AddField(
            model_name='orders',
            name='currency',
            field=models.CharField(choices=[('€', 'Euro'), ('$', 'Dollars')], default='$', max_length=1),
        ),
    ]
