# Generated by Django 4.2.4 on 2023-09-18 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0059_orderdetails_good_name_orderdetails_user_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='delivery_address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='orders',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
