# Generated by Django 4.2.4 on 2023-09-19 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0068_alter_orderdetails_cost_alter_orderdetails_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defects',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='goods',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.categories'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='messages',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
