# Generated by Django 4.2.4 on 2023-09-19 09:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0070_alter_sales_image_alter_sales_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='cost',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='good',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.goods'),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
