# Generated by Django 4.2.4 on 2023-09-19 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0072_alter_orders_phone_alter_orders_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='currency',
            field=models.CharField(choices=[('€', 'Euro'), ('$', 'Dollars')], default='$', max_length=1),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
