# Generated by Django 4.2.4 on 2023-09-19 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0076_alter_defects_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='currency',
            field=models.CharField(default='$', max_length=1),
        ),
    ]
