# Generated by Django 4.2.4 on 2023-09-19 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0077_alter_shoppingcart_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='currency',
        ),
    ]
