# Generated by Django 4.2.4 on 2023-09-19 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0078_remove_orders_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='currency',
            field=models.CharField(default='$', max_length=1),
        ),
    ]
