# Generated by Django 4.2.4 on 2023-09-19 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0079_alter_orderdetails_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='catalog'),
        ),
        migrations.AlterField(
            model_name='mainpagegallery',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='main page gallery'),
        ),
    ]
